routes/web.php
<?php

use App\Http\Controllers\Board\BoardController;
use App\Http\Controllers\Board\BoardExcelController;
use App\Http\Controllers\IndexController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', IndexController::class)
    ->name('index');


Route::get('/boards/excel', [BoardExcelController::class, 'show']);
Route::post('/boards/excel', [BoardExcelController::class, 'store'])
    ->name('boards.excel');

Route::resource('/boards', BoardController::class);

app/Models/Board.php
<?php

namespace App\Models;

use Eloquent;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Support\Carbon;

/**
 * App\Models\Board
 *
 * @property int $id
 * @property int $user_id 작성자
 * @property string $subject 제목
 * @property string $contents 내용
 * @property int $is_private 비공개 여부
 * @property int $view_count 조회수
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property string|null $deleted_at
 * @property-read Collection|\App\Models\File[] $files
 * @property-read int|null $files_count
 * @property-read \App\Models\User $user
 * @method static Builder|Board newModelQuery()
 * @method static Builder|Board newQuery()
 * @method static Builder|Board public()
 * @method static Builder|Board query()
 * @method static Builder|Board whereContents($value)
 * @method static Builder|Board whereCreatedAt($value)
 * @method static Builder|Board whereDeletedAt($value)
 * @method static Builder|Board whereId($value)
 * @method static Builder|Board whereIsPrivate($value)
 * @method static Builder|Board whereSubject($value)
 * @method static Builder|Board whereUpdatedAt($value)
 * @method static Builder|Board whereUserId($value)
 * @method static Builder|Board whereViewCount($value)
 * @mixin Eloquent
 */
class Board extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'subject',
        'contents',
        'is_private',
    ];

    public const VIEW_DESCRIPTION = [
        self::VIEW_PUBLIC => '공개',
        self::VIEW_PRIVATE => '비공개',
    ];

    public const VIEW_PUBLIC = 0;
    public const VIEW_PRIVATE = 1;

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return string
     */
    public function viewCount(): string
    {
        return number_format($this->view_count);
    }

    /**
     * @return MorphMany
     */
    public function files(): MorphMany
    {
        return $this->morphMany(File::class, 'fileable');
    }

    /**
     * @param Builder $query
     * @return Builder
     */
    public function scopePublic(Builder $query): Builder
    {
        return $query->where('is_private', false);
    }
}

app/Http/Controllers/Board/BoardController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use App\Http\Requests\Board\BoardStoreRequest;
use App\Models\Board;
use App\Services\Board\BoardStoreService;
use App\Services\Board\BoardUploadService;
use App\Services\Board\Dto\BoardStoreDto;
use App\Services\Board\SearchBoardService;
use DB;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Http\UploadedFile;
use Throwable;

class BoardController extends Controller
{
    /**
     * @var SearchBoardService
     */
    private $searchBoardService;
    /**
     * @var BoardStoreService
     */
    private $boardStoreService;
    /**
     * @var BoardUploadService
     */
    private $boardUploadService;

    /**
     * BoardController constructor.
     * @param SearchBoardService $searchBoardService
     * @param BoardStoreService $boardStoreService
     * @param BoardUploadService $boardUploadService
     */
    public function __construct(
        SearchBoardService $searchBoardService,
        BoardStoreService $boardStoreService,
        BoardUploadService $boardUploadService
    ) {
        $this->searchBoardService = $searchBoardService;
        $this->boardStoreService = $boardStoreService;
        $this->boardUploadService = $boardUploadService;
    }

    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $boards = $this->searchBoardService->public()->with('user')->paginate(10);

        return view('boards.index', compact('boards'));
    }

    /**
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('boards.create');
    }

    /**
     * @param BoardStoreRequest $request
     * @return RedirectResponse
     * @throws Throwable
     */
    public function store(BoardStoreRequest $request): RedirectResponse
    {
        if (!auth()->check()) {
            throw new Exception('로그인이 필요합니다.', '403');
        }

        try {
            DB::beginTransaction();

            $boardStoreDto = new BoardStoreDto(
                $request->user()->id,
                $request->get('subject'),
                $request->get('contents'),
                $request->get('is_private')
            );

            /** @var Board $board */
            $board = $this->boardStoreService->save($boardStoreDto);
            if (!$board) {
                throw new Exception('게시글이 등록되지 않았습니다.', '500');
            }

            if ($request->hasFile('files')) {
                foreach ($request->file('files') as $file) {
                    /** @var UploadedFile $file */
                    $fileName = $board->getTable() . "_" . $board->id . "_" . $file->hashName();
                    $fileNameWithPath = $file->storePubliclyAs(
                        'board',
                        $board->getTable() . "_" . $board->id . "_" . $file->hashName()
                    );

                    if (!$fileNameWithPath) {
                        throw new Exception(500, '파일 업로드 실패');
                    }

                    $this->boardUploadService->setUser($request->user());
                    $this->boardUploadService->setFile($file, $fileName);
                    $this->boardUploadService->setCategory('board');

                    if (!$board->files()->save($this->boardUploadService->getFile())) {
                        throw new Exception(500, '파일 정보 저장 실패');
                    }
                }
            }
            DB::commit();

            return redirect()->route('boards.show', $board);
        } catch (Exception $e) {
            DB::rollBack();
            report($e);

            return redirect()->back();
        }
    }

    /**
     * @param Board $board
     * @return Application|Factory|View
     */
    public function show(Board $board)
    {
        return view('boards.show', compact('board'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Board $board
     * @return Response
     */
    public function edit(Board $board): Response
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Board $board
     * @return Response
     */
    public function update(Request $request, Board $board): Response
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Board $board
     * @return Response
     */
    public function destroy(Board $board): Response
    {
        //
    }
}

app/Http/Controllers/Board/BoardExcelController.php
<?php

namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use App\Http\Requests\Board\BoardExcelRequest;
use App\Models\Board;
use App\Services\Board\BoardStoreService;
use App\Services\Board\Dto\BoardStoreDto;
use Box\Spout\Common\Exception\IOException;
use Box\Spout\Common\Exception\UnsupportedTypeException;
use Box\Spout\Reader\Exception\ReaderNotOpenedException;
use DB;
use Exception;
use Illuminate\Http\RedirectResponse;
use Rap2hpoutre\FastExcel\FastExcel;
use Throwable;

class BoardExcelController extends Controller
{
    /**
     * @var BoardStoreService
     */
    private $boardStoreService;

    /**
     * BoardExcelController constructor.
     * @param BoardStoreService $boardStoreService
     */
    public function __construct(BoardStoreService $boardStoreService)
    {
        $this->boardStoreService = $boardStoreService;
    }

    public function show()
    {
        return view('boards.excel-show');
    }

    /**
     * @param BoardExcelRequest $request
     * @return RedirectResponse
     * @throws IOException
     * @throws UnsupportedTypeException
     * @throws ReaderNotOpenedException
     * @throws Throwable
     */
    public function store(BoardExcelRequest $request): RedirectResponse
    {
        $excelFile = $request->file('excel');

        $rows = (new FastExcel())->import($excelFile);

        try {
            DB::beginTransaction();
            foreach ($rows as $row) {
                if ($this->isNullValue($row['subject'])) {
                    throw new Exception('제목이 비어있는 행이 있습니다.', 400);
                }

                if ($this->isNullValue($row['contents'])) {
                    throw new Exception('내용이 비어있는 행이 있습니다.', 400);
                }

                if ($this->isNullValue($row['is_private']) || $this->isNotBoolType($row['is_private'])) {
                    $row['is_private'] = Board::VIEW_PUBLIC;
                }

                $boardStoreDto = new BoardStoreDto(
                    $request->user()->id,
                    $row['subject'],
                    $row['contents'],
                    $row['is_private']
                );

                if (!$this->boardStoreService->save($boardStoreDto)) {
                    throw new Exception('글쓰기에 실패하였습니다.', 400);
                }
            }

            DB::commit();

            return redirect()->route('boards.index');
        } catch (Exception $e) {
            DB::rollBack();
            report($e);

            return redirect()->back();
        }
    }

    /**
     * @param $subject
     * @return bool
     */
    private function isNullValue($subject): bool
    {
        return $subject === "";
    }

    /**
     * @param $is_private
     * @return bool
     */
    private function isNotBoolType($is_private): bool
    {
        return !($is_private === 0 || $is_private === 1);
    }
}

resources/views/boards/create.blade.php
@php

    @endphp

@extends('layouts.app')

@section('title')

@endsection

@push('css')

@endpush

@section('content')
    <div class="container mx-auto">
        <form action="{{ route('boards.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <hr>
            <label>
                제목 :
                <input type="text" name="subject">
            </label>
            <hr>
            <label>
                내용 :
                <textarea name="contents" cols="30" rows="10"></textarea>
            </label>
            <hr>
            <label>
                파일 업로드1 :
                <input type="file" name="files[]">
            </label>
            <hr>
            <label>
                파일 업로드2 :
                <input type="file" name="files[]">
            </label>
            <hr>
            <label>
                비공개 여부 :
                <input type="hidden" name="is_private" value="{{ \App\Models\Board::VIEW_PUBLIC }}" checked>
                <input type="checkbox" name="is_private" value="{{ \App\Models\Board::VIEW_PRIVATE }}">
            </label>
            <hr>
            <button type="submit">등록</button>
        </form>
    </div>
@endsection

@push('js')

@endpush

resources/views/boards/excel-show.blade.php
@php

    @endphp

@extends('layouts.app')

@section('title')

@endsection

@push('css')

@endpush

@section('content')
    <div class="container mx-auto">
        <form action="{{ route('boards.excel') }}" method="post" enctype="multipart/form-data">
            @csrf
            <input type="file" name="excel">
            <hr>
            <button type="submit">등록</button>
        </form>
    </div>
@endsection

@push('js')

@endpush

resources/views/boards/index.blade.php
@php
    /**
    * @var \App\Models\Board[] $boards
    */
@endphp

@extends('layouts.app')

@section('title')

@endsection

@push('css')

@endpush

@section('content')
    <div class="container mx-auto">
        <table class="table-auto">
            <thead>
            <tr>
                <th class="w-1/12">번호</th>
                <th>제목</th>
                <th class="w-1/12">작성자</th>
                <th class="w-1/12">조회수</th>
                <th class="w-1/12">작성일시</th>
            </tr>
            </thead>
            <tbody>
            @forelse($boards as $board)
                <tr class="text-center">
                    <td>{{ $board->id }}</td>
                    <td>
                        <a href="{{ route('boards.show', $board) }}">
                            {{ $board->subject }}
                        </a>
                    </td>
                    <td>{{ $board->user->name }}</td>
                    <td>{{ $board->viewCount() }}</td>
                    <td>{{ $board->created_at->diffForHumans() }}</td>
                </tr>
            @empty
                <tr class="cursor-pointer">
                    <td class="w-1" colspan="3">not Items</td>
                </tr>
            @endforelse
            </tbody>
            <tfoot>
            <tr>
                <td colspan="5">
                    @if($boards->hasPages())
                        {{ $boards->links() }}
                    @endif
                </td>
            </tr>
            </tfoot>
        </table>
    </div>
@endsection

@push('js')

@endpush

resources/views/boards/show.blade.php
@php
    /**
    * @var \App\Models\Board $board
    */
@endphp

@extends('layouts.app')

@section('title')

@endsection

@push('css')

@endpush

@section('content')
    <div class="container mx-auto">
        <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl">
            <div class="md:flex">
                <div class="md:flex-shrink-0">
                    <img class="h-48 w-full object-cover md:w-48" src="#" alt="Man looking at item at a store">
                </div>
                <div class="p-8">
                    <div class="uppercase tracking-wide text-sm text-indigo-500 font-semibold">
                        {{ $board->subject }}
                    </div>
                    <p class="block mt-1 text-lg leading-tight font-medium text-black">
                        {{ $board->contents }}
                    </p>
                    @foreach($board->files as $file)
                        <p class="mt-2 text-gray-500">
                            {{ $loop->iteration }}.
                            <a href="#">
                                {{ $file->origin_name }}
                            </a>
                        </p>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')

@endpush